use_frameworks!

platform :ios, '12.0'

target 'LHypothesis_Example' do
  pod 'LHypothesis/Firebase', :path => '../'
  pod 'LHypothesis/AppsFlyer', :path => '../'
  
  target 'LHypothesis_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end
end
