use_frameworks!

platform :ios, '13.0'

target 'LHypothesis-Example' do
  pod 'LHypothesis', :path => '../', :testspecs => ['Tests']
  pod 'LHypothesis/Firebase', :path => '../'
  pod 'LHypothesis/AppsFlyer', :path => '../'
end
