coverage_service: cobertura_xml
xcodeproj: LHypothesis.xcodeproj
workspace: LHypothesis.xcworkspace
scheme: LHypothesisTests-iOS
source_directory: Classes
output_directory: reports
ignore:
  - Classes/Providers/*
