coverage_service: cobertura_xml
arch: arm64
xcodeproj: Example/LHypothesis.xcodeproj
workspace: Example/LHypothesis.xcworkspace
scheme: LHypothesis-Example
# configuration: Release
source_directory: Classes
output_directory: reports
ignore:
  - Classes/Providers/*
  - Example/LHypothesis/*
  - Example/Pods/*
  - Example/Tests/*
