coverage_service: cobertura_xml
arch: x86_64
xcodeproj: Example/LHypothesis.xcodeproj
workspace: Example/LHypothesis.xcworkspace
scheme: LHypothesis-Example
configuration: Release
source_directory: LHypothesis/Classes
output_directory: reports
ignore:
  - Example/LHypothesis/*
  - Example/Pods/*
  - Example/Tests/*
