default_platform(:ios)

platform :ios do
  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  desc "Library lint"
  lane :lib_lint do
    pod_lib_lint(allow_warnings: true, fail_fast: true)
  end

  desc "Create code coverage report"
  lane :code_coverage do
    scan(workspace: "LHypothesis.xcworkspace", scheme: "LHypothesisTests-iOS", devices: ["iPhone 14"], clean: true)
    slather
  end

  desc "Complete release. Create tag and push pod"
  lane :complete_release do
    podspecName = "LHypothesis.podspec"
    version = version_get_podspec(path: podspecName)
    unless git_tag_exists(tag: version)
      add_git_tag(tag: "#{version}")
      push_git_tags
      pod_push(allow_warnings: true, verbose: true)
    end
  end

  def release(type)
	  podspecName = "LHypothesis.podspec"
	  ensure_git_branch(
      branch: '^release/.*$'
    )
	  ensure_git_status_clean
    pod_lib_lint(allow_warnings: true, fail_fast: true, platforms: 'ios')
    version = version_bump_podspec(path: podspecName, bump_type: type)
    git_add(path: podspecName)
    git_commit(path: [podspecName], message: "#{version} release")
    push_to_git_remote
  end

  def carthage_release
    carthage(command: "build", platform: "Mac,iOS,tvOS", configuration: "Release", use_xcframeworks: true, no_skip_current: true)
    git_add(path: './Carthage/*')
  end
end
