default_platform(:ios)

platform :ios do
  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  desc "Build, test and generate code coverage"
  lane :code_coverage do
    cocoapods(repo_update: true, silent: true, podfile: 'Example/Podfile')
    scan(
      workspace: 'Example/LHypothesis.xcworkspace',
      scheme: 'LHypothesis-Example',
      devices: ["iPhone 14"]
    )
    slather
  end

  desc "Library lint"
  lane :lib_lint do
    pod_lib_lint(allow_warnings: true, fail_fast: true)
  end

  desc "Complete release. Create tag and push pod"
  lane :complete_release do
    podspecName = "LHypothesis.podspec"
    version = version_get_podspec(path: podspecName)
    add_git_tag(tag: "#{version}")
    push_git_tags
    pod_push(allow_warnings: true, verbose: true)
  end

  def release(type)
	  podspecName = "LHypothesis.podspec"
	  ensure_git_branch(
      branch: '^release/.*$'
    )
	  ensure_git_status_clean
    pod_lib_lint(allow_warnings: true, fail_fast: true, platforms: 'ios')
    version = version_bump_podspec(path: podspecName, bump_type: type)
    cocoapods(repo_update: true, silent: true, podfile: 'Example/Podfile')
    carthage(command: "build", no_skip_current: true, use_xcframeworks: true, platform: 'Mac,iOS,tvOS')
    git_add(path: podspecName)
    git_commit(path: [podspecName], message: "#{version} release")
    push_to_git_remote
  end
end
