name: main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
    
env:
  FASTLANE_XCODE_LIST_TIMEOUT: 12

jobs:
  code-coverage:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: bundle install
     - name: Build and test
       run: swift test --enable-code-coverage
     - name: Coverage output
       run: xcrun llvm-cov export -format="lcov" .build/debug/LHypothesisPackageTests.xctest/Contents/MacOS/LHypothesisPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
     - uses: codecov/codecov-action@v3
       with:
          files: ./info.lcov
          fail_ci_if_error: true
