name: stable-main

on:
  push:
    branches: [ "main" ]
    
env:
  FASTLANE_XCODE_LIST_TIMEOUT: 12

jobs:
    
  code-coverage:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: bundle install
     - name: Build, test and send code coverage
       run: bundle exec fastlane code_coverage
     - uses: codecov/codecov-action@v3
       with:
          files: ./reports/cobertura.xml
          fail_ci_if_error: true
